site_name: DealSphere Documentation
site_description: Complete Documentation for the DealSphere Platform (APIs, architecture, planning, QA, product, tech)
site_author: DealSphere Team
repo_url: https://github.com/DealSphere-Inc/dealsphere-platform-docs

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico  
  palette:
    - scheme: default
      primary: blue
      accent: cyan
    - scheme: slate
      primary: blue
      accent: cyan
  toggle:
    icon: material/weather-night
    name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate

nav:
  - Home: README.md

  - Architecture Decision Records (ADRs):
      - ADR Master Index: adr/README.md
      - ADR-000-template: adr/ADR-000-template.md
      - Java 17 Runtime: adr/ADR-0001-java-17-runtime.md
      - R3 Corda 5 DLT Platform: adr/ADR-0002-r3-corda-5-dlt-platform.md
      - Docker Compose Phase 1 Orchestration: adr/ADR-0003-docker-compose-phase1-orchestration.md
      - Service Framework Defaults: adr/ADR-0004-service-framework-defaults.md

  - Planning:
      - Phase 1 Epics: planning/phase1-epics.md
      - Delivery Plan (12 Weeks): planning/delivery-plan-12weeks-tdd.md

  - Product:
      - Phase 1 PRD: product/Phase1_PRD.md
      # Add more as needed after confirming filenames

  - QA & Compliance:
      - Functional Test Cases: qa/Phase1_Functional_Test_Cases.md
      # Add more as needed after confirming filenames

  - Development:
      - Local CI/CD Setup: development/local-cicd-setup.md
      - GitHub Actions: development/github-actions.md
      - Cypress E2E Testing: development/cypress-e2e-testing.md

  - Deployment:
      - Overview: deployment/README.md
      - Production Deployment: deployment/production-deployment.md
      - Cloud Infrastructure: deployment/cloud-infrastructure.md
      - Environment Management: deployment/environment-management.md
      - Observability & Monitoring: deployment/observability-monitoring.md
      - Security & Secrets: deployment/security-secrets.md

  - Technical Documentation:
      - Tech Landscape (MVP): tech/tech-landscape.md
      # Add more as needed after confirming filenames

markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - toc:
      permalink: true
  - tables
  - def_list
  - attr_list

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DealSphere-Inc
